model = "gpt-5.5"
model_reasoning_effort = "xhigh"
plan_mode_reasoning_effort = "xhigh"
sandbox_mode = "workspace-write"
approval_policy = "on-request"
service_tier = "fast"
approvals_reviewer = "auto_review"
[projects."/Users/ryreese/Documents/nvidia/nvalchemi-toolkit"]
trust_level = "trusted"

[projects."/Users/ryreese/Documents/nvidia/alchemi-playbook"]
trust_level = "trusted"

[projects."/Users/ryreese/dotfiles"]
trust_level = "trusted"

[projects."/Users/ryreese/Documents/nvidia/academic-grants"]
trust_level = "trusted"

[projects."/Users/ryreese/Documents/nvidia/ntrain"]
trust_level = "trusted"

[plugins."github@openai-curated"]
enabled = true

[plugins."life-science-research@openai-curated"]
enabled = true

[plugins."slack@openai-curated"]
enabled = true

[plugins."superpowers@openai-curated"]
enabled = true

[plugins."nvidia@openai-curated"]
enabled = true

[plugins."vault@vault"]
enabled = true

[marketplaces.vault]
source_type = "local"
source = "/Users/ryreese/Documents"

[tui]
status_line = ["current-dir", "git-branch", "branch-changes", "model-with-reasoning", "permissions", "approval-mode", "context-used"]
status_line_use_colors = true
theme = "bamboo-multiplex"
vim_mode_default = true

[tui.keymap.global]
copy = "ctrl-t"
open_transcript = "ctrl-o"

[tui.keymap.editor]
insert_newline = ["ctrl-j", "ctrl-m", "enter", "shift-enter", "alt-enter"]

[tui.model_availability_nux]
"gpt-5.5" = 4

[mcp_servers.maas_gitlab]
url = "https://maas.prd.astra.nvidia.com/maas/gitlab/mcp"

[mcp_servers.maas_gdrive]
url = "https://maas.prd.astra.nvidia.com/maas/gdrive/mcp"

[mcp_servers.maas_onedrive]
url = "https://maas.prd.astra.nvidia.com/maas/onedrive/mcp"

[mcp_servers.maas_confluence]
url = "https://maas.prd.astra.nvidia.com/maas/confluence/mcp"

[mcp_servers.maas_sharepoint]
url = "https://maas.prd.astra.nvidia.com/maas/sharepoint/mcp"

[mcp_servers.maas_outlook]
url = "https://maas.prd.astra.nvidia.com/maas/outlook/mcp"

[mcp_servers.maas_outlook.oauth]
client_id = "eci-prd-pub-160c4545-f84f-4483-bf7c-d2450e5c0216"

[mcp_servers.maas_slack]
url = "https://maas.prd.astra.nvidia.com/maas/slack/mcp"

[mcp_servers.maas_slack.oauth]
client_id = "eci-prd-pub-160c4545-f84f-4483-bf7c-d2450e5c0216"

[mcp_servers.maas_nsight_cuda]
url = "https://maas.prd.astra.nvidia.com/maas/nsight_cuda/mcp"

[notice]
fast_default_opt_out = true

[features]
terminal_resize_reflow = true
memories = true
